config/routes.rb
Rails.application.routes.draw do
  root 'patients#index'
  resources :patients do
    resources :locations
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :patient
  validates :code, length:{ maximum: 10}
  validates :name, presence:true, length:{ maximum: 80}
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_one :location
  STATUS =[["Initial","初期"], ["Referred","转诊"], ["Treatment","治疗"], ["Closed","关闭"]]
  STATUS_VALUES = STATUS.map{|s| s[0]}
  STATUS_NAMES = STATUS.map{|s| s[1]}
  validates :first_name, presence: true, length:{ maximum: 30}
  validates :middle_name, length: { maximum: 10}
  validates :last_name, presence: true, length: { maximum: 30}
  validates :status, presence: true, :inclusion => {:in => STATUS_VALUES}
  validates :gender, presence: true

  def status_name
    result = ''
    STATUS.each do |s|
      if s[0] == self.status.to_s
        result = s[1]
      end
    end
    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def set_locale
    if params[:locale] && I18n.available_locales.include?( params[:locale].to_sym )
      session[:locale] = params[:locale]
    end

    I18n.locale = session[:locale] || I18n.default_locale
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_patient
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  def index
    @locations = Location.all
  end

  def show
    respond_with @patient,@location
  end

  def new
    @location = Location.new
  end

  def edit
  end

  def create
    debugger
    @location = @patient.locations.build(location_params)
    respond_to do |format|
      if @location.save
        format.html { redirect_to [@patient,@location], notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_patient
      @patient = Patient.find(params[:patient_id]) if params[:patient_id].present?
    end

    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:patient_id, :code, :name)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  # respond_to :html
  def index
    # @patients = Patient.all
    @q = Patient.search(params[:q])
    @patients = @q.result(distinct: true).paginate(page: params[:page])
  end


  def show
  end

  def new
    @patient = Patient.new
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end

  private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:first_name, :middle_name, :last_name, :medical_record_num, :birth, :gender, :status, :viewed_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Patients</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.haml
= form_for [@patient, @location] do |f|
  - if @location.errors.any?
    #error_explanation
      %h2= "#{pluralize(@location.errors.count, "error")} prohibited this location from being saved:"
      %ul
        - @location.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :code
    = f.text_field :code
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/locations/edit.html.haml
%h1 Editing location

= render 'form'

= link_to 'Show', ([@patient,@location])
\|
= link_to 'Back', patient_locations_path

app/views/locations/index.html.haml
%table
  %thead
    %tr
      %th Patient
      %th Code
      %th Name

  %tbody
    - @locations.each do |location|
      %tr
        %td= location.patient_id
        %td= location.code
        %td= location.name
        %td= link_to 'Show', location
        %td= link_to 'Edit', edit_location_path(location)
        %td= link_to 'Destroy', location, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to '新建', new_patient_location_path

app/views/locations/new.html.haml
%h1 新建位置

= render 'form'

= link_to '返回', patient_locations_path(@patient)

app/views/locations/show.html.haml
%p#notice= notice

%p
  %b Patient:
  = @location.patient_id
%p
  %b Code:
  = @location.code
%p
  %b Name:
  = @location.name

= link_to '编辑', edit_patient_location_path(@location)
\|
= link_to '返回', patient_locations_path(@patient,@location)

app/views/patients/_form.html.haml
= simple_form_for (@patient) do |f|
  .form-inputs
    = f.input :first_name
    = f.input :middle_name
    = f.input :last_name
    = f.input :birth, as: :date
    = f.input :status, collection: Patient::STATUS.map{|x| [x[1], x[0]]}, include_blank: false
    = f.collection_radio_buttons :gender, [["Male", '1'] ,["Female", '2']], :first, :last, { item_wrapper_tag: false } do |b|
      = b.label(:class => 'btn btn-primary span3'){ b.radio_button + b.text }
    = f.button :submit, :class=>"btn btn-default"

app/views/patients/edit.html.haml
%h1 更新
= render 'form'
= link_to '查看', @patient
|
= link_to '返回', patients_path

app/views/patients/index.html.haml
%p#notice= notice
%h1 患者列表

%table.table.table-striped
  %thead
    %tr
      %th= Patient.human_attribute_name(:medical_record_num)
      %th= Patient.human_attribute_name(:fullname)
      %th= Patient.human_attribute_name(:age)
      %th= Patient.human_attribute_name(:gender)
      %th= Patient.human_attribute_name(:status)
      %th= Patient.human_attribute_name(:location)
  %tbody
    - @patients.each do |patient|
      %tr
        %td= "MR#{patient.id}"
        %td= patient.first_name+" "+patient.middle_name+" "+patient.last_name
        %td= DateTime.now.strftime('%Y').to_i-patient.birth.strftime('%Y').to_i
        %td= patient.gender
        %td= patient.status_name
        %td= patient.location
        %th
          = link_to '详情', patient, class: 'btn btn-info'
          = link_to '更新', edit_patient_path(patient), class: 'btn btn-success'
          = link_to '删除', patient, method: :delete, data: { confirm: '确定删除?' }, class: 'btn btn-danger'

%br
.row-fluid
  = link_to '新建', new_patient_path

  = link_to "中文版", :controller => controller_name, :action => action_name, :locale => "zh-CN"
  = link_to "English", :controller => controller_name, :action => action_name, :locale => "en"

app/views/patients/new.html.haml
%h1 新建
= render 'form'
= link_to '返回', patients_path

app/views/patients/show.html.haml
%p#notice= notice
%p
  %strong= Patient.human_attribute_name(:medical_record_num) + ':'
  = @patient.medical_record_num
%p
  %strong= Patient.human_attribute_name(:first_name) + ':'
  = @patient.first_name
%p
  %strong= Patient.human_attribute_name(:middle_name) + ':'
  = @patient.middle_name
%p
  %strong= Patient.human_attribute_name(:last_name) + ':'
  = @patient.last_name
%p
  %strong= Patient.human_attribute_name(:birth) + ':'
  = @patient.birth.strftime('%Y-%m-%d')
%p
  %strong= Patient.human_attribute_name(:gender) + ':'
  = @patient.gender
%p
  %strong= Patient.human_attribute_name(:status) + ':'
  = @patient.status_name
%p
  %strong= Patient.human_attribute_name(:location) + ':'
  = @patient.location
%p
  %strong= Patient.human_attribute_name(:viewed_count) + ':'
  = @patient.viewed_count
= link_to '编辑', edit_patient_path(@patient)
|
= link_to '返回', patients_path